from __future__ import annotations
import argparse, hashlib, json, time
from pathlib import Path
from collections import Counter
from charitygraph.openai_client import responses_create, estimate_response_cost

FACETS=("operational_activity","participation","fundraising_mode","governance_practice","capability_access","ethos_conduct","evaluation_method","other_native_residual")
PROMPT=("Review canonical semantic objects for optional CharityGraph Native overlay instances. Each object already has canonical representation. Return one review per local key, with zero or more overlays. An overlay must add a reusable analytical activity, mode, practice, participation, fundraising, capability, ethos or evaluation distinction beyond canonical representation. Never output names, IDs, legal/regulatory facts, amounts, dates, locations, beneficiary counts, evidence metadata, source identity, or ordinary structural relationship roles. Native is an optional overlay. Return strict JSON only.")
def schema():
    ov={"type":"object","additionalProperties":False,"required":["overlay_statement","facet","analytic_dimension","why_adds_value_beyond_canonical","anti_duplication_boundary","qualification","uncertainty"],"properties":{"overlay_statement":{"type":"string"},"facet":{"type":"string","enum":list(FACETS)},"analytic_dimension":{"type":"string"},"why_adds_value_beyond_canonical":{"type":"string"},"anti_duplication_boundary":{"type":"string"},"qualification":{"type":"string"},"uncertainty":{"type":["string","null"]}}}
    rec={"type":"object","additionalProperties":False,"required":["local_key","overlays"],"properties":{"local_key":{"type":"string","pattern":"^O[0-9]{2}$"},"overlays":{"type":"array","items":ov}}}
    return {"type":"object","additionalProperties":False,"required":["reviews"],"properties":{"reviews":{"type":"array","items":rec}}}
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--runtime',default=r'C:\CharityGraph-runtime\native-induction-v5-overlay-lifecycle'); ap.add_argument('--objects',default=r'C:\CharityGraph-runtime\native-induction-v4r-faceted-disposition-repair\stage-a-dispositions.json'); a=ap.parse_args(); root=Path(a.runtime); (root/'raw').mkdir(parents=True,exist_ok=True)
    rows=json.loads(Path(a.objects).read_text(encoding='utf-8')); objs=[]
    for row in rows:
        for i,o in enumerate(row.get('objects',[])): objs.append({'canonical_object_id':f"{row['source_observation_id']}:{i+1}",'organisation':row['subject'],'statement':o['statement'],'representation_family':o.get('representation_family')})
    counts=Counter(x['organisation'] for x in objs); order=sorted(counts,key=lambda n:(-counts[n],n)); train=set(order[:3]); hold=set(order[3:]); split={'organisations':[{'organisation':n,'role':'train' if n in train else 'holdout','object_count':counts[n]} for n in order],'training_object_count':sum(counts[n] for n in train),'holdout_object_count':sum(counts[n] for n in hold),'source_sha256':hashlib.sha256(Path(a.objects).read_bytes()).hexdigest()}; (root/'v5-organisation-split.json').write_text(json.dumps(split,ensure_ascii=False,indent=2),encoding='utf-8')
    trainobjs=[x for x in objs if x['organisation'] in train]; calls=[]; valid=[]; total=0
    for ci in range(0,len(trainobjs),12):
        batch=trainobjs[ci:ci+12]; keyed=[{'local_key':f'O{i:02d}',**x} for i,x in enumerate(batch,1)]; inp=PROMPT+'\n\nOBJECTS:\n'+json.dumps([{k:x[k] for k in ('local_key','organisation','representation_family','statement')} for x in keyed],ensure_ascii=False); started=time.time(); res=responses_create(model='gpt-5.6-luna',input_text=inp,text_format={'type':'json_schema','name':'native_overlay_review_v5','schema':schema()},max_output_tokens=7000,max_attempts=1,timeout_seconds=300,reasoning={'effort':'none'}); latency=time.time()-started; (root/'raw'/f'luna-harvest-{ci//12+1:02d}.json').write_text(res.output_text,encoding='utf-8'); err=None
        try: parsed=json.loads(res.output_text); reviews=parsed['reviews']; keys=[r.get('local_key') for r in reviews]; expected={x['local_key'] for x in keyed}; assert len(keys)==len(set(keys)) and set(keys)==expected
        except Exception as e: reviews=[]; err=str(e)
        for r,x in zip(reviews,keyed): r.update({k:x[k] for k in ('canonical_object_id','organisation','representation_family')})
        valid.extend(reviews); cost=estimate_response_cost(res.model,res.usage) or 0; total+=float(cost); calls.append({'label':f'luna-harvest-{ci//12+1:02d}','model':res.model,'reasoning':'none','max_output_tokens':7000,'status':'completed' if not err else 'invalid','response_id':res.response_id,'input_tokens':res.usage.input_tokens,'output_tokens':res.usage.output_tokens,'cost_usd':str(cost),'latency_seconds':round(latency,3),'transport_attempts':res.transport_requests,'error':err})
    facets=Counter(o['facet'] for r in valid for o in r.get('overlays',[])); summary={'experiment_id':'native-induction-v5-overlay-lifecycle','training_organisations':sorted(train),'holdout_organisations':sorted(hold),'training_canonical_objects':len(trainobjs),'holdout_canonical_objects':len(objs)-len(trainobjs),'luna_calls':calls,'valid_review_records':len(valid),'overlay_instances':sum(len(r.get('overlays',[])) for r in valid),'overlays_by_facet':dict(facets),'zero_one_multi':[sum(not r.get('overlays') for r in valid),sum(len(r.get('overlays',[]))==1 for r in valid),sum(len(r.get('overlays',[]))>1 for r in valid)],'holdout_exposed':False}; (root/'experiment-summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2),encoding='utf-8'); print(json.dumps({'calls':len(calls),'valid':len(valid),'overlays':summary['overlay_instances'],'facets':dict(facets),'cost':total},indent=2))
if __name__=='__main__': main()
